// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: room.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 踢人请求
type KickUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`             // 房间ID
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 被踢用户ID
	OperatorId    uint64                 `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 操作者ID
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                            // 踢人原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserReq) Reset() {
	*x = KickUserReq{}
	mi := &file_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserReq) ProtoMessage() {}

func (x *KickUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserReq.ProtoReflect.Descriptor instead.
func (*KickUserReq) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0}
}

func (x *KickUserReq) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *KickUserReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *KickUserReq) GetOperatorId() uint64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *KickUserReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 踢人响应
type KickUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 操作是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserResp) Reset() {
	*x = KickUserResp{}
	mi := &file_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserResp) ProtoMessage() {}

func (x *KickUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserResp.ProtoReflect.Descriptor instead.
func (*KickUserResp) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1}
}

func (x *KickUserResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *KickUserResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 禁言请求
type MuteUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                   // 房间ID
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // 被禁言用户ID
	OperatorId    uint64                 `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`       // 操作者ID
	DurationType  int32                  `protobuf:"varint,4,opt,name=duration_type,json=durationType,proto3" json:"duration_type,omitempty"` // 禁言时长类型：1-1小时，2-24小时，3-永久
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`                                  // 禁言原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuteUserReq) Reset() {
	*x = MuteUserReq{}
	mi := &file_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuteUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuteUserReq) ProtoMessage() {}

func (x *MuteUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuteUserReq.ProtoReflect.Descriptor instead.
func (*MuteUserReq) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{2}
}

func (x *MuteUserReq) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *MuteUserReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MuteUserReq) GetOperatorId() uint64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *MuteUserReq) GetDurationType() int32 {
	if x != nil {
		return x.DurationType
	}
	return 0
}

func (x *MuteUserReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 禁言响应
type MuteUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 操作是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuteUserResp) Reset() {
	*x = MuteUserResp{}
	mi := &file_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuteUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuteUserResp) ProtoMessage() {}

func (x *MuteUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuteUserResp.ProtoReflect.Descriptor instead.
func (*MuteUserResp) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{3}
}

func (x *MuteUserResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MuteUserResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 解除禁言请求
type UnmuteUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`             // 房间ID
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 被解除禁言用户ID
	OperatorId    uint64                 `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 操作者ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmuteUserReq) Reset() {
	*x = UnmuteUserReq{}
	mi := &file_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmuteUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmuteUserReq) ProtoMessage() {}

func (x *UnmuteUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmuteUserReq.ProtoReflect.Descriptor instead.
func (*UnmuteUserReq) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{4}
}

func (x *UnmuteUserReq) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *UnmuteUserReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnmuteUserReq) GetOperatorId() uint64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

// 解除禁言响应
type UnmuteUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 操作是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmuteUserResp) Reset() {
	*x = UnmuteUserResp{}
	mi := &file_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmuteUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmuteUserResp) ProtoMessage() {}

func (x *UnmuteUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmuteUserResp.ProtoReflect.Descriptor instead.
func (*UnmuteUserResp) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{5}
}

func (x *UnmuteUserResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnmuteUserResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_room_proto protoreflect.FileDescriptor

const file_room_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"room.proto\x12\x04room\"x\n" +
	"\vKickUserReq\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x1f\n" +
	"\voperator_id\x18\x03 \x01(\x04R\n" +
	"operatorId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"B\n" +
	"\fKickUserResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9d\x01\n" +
	"\vMuteUserReq\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x1f\n" +
	"\voperator_id\x18\x03 \x01(\x04R\n" +
	"operatorId\x12#\n" +
	"\rduration_type\x18\x04 \x01(\x05R\fdurationType\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"B\n" +
	"\fMuteUserResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"b\n" +
	"\rUnmuteUserReq\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x1f\n" +
	"\voperator_id\x18\x03 \x01(\x04R\n" +
	"operatorId\"D\n" +
	"\x0eUnmuteUserResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa5\x01\n" +
	"\x04Room\x121\n" +
	"\bKickUser\x12\x11.room.KickUserReq\x1a\x12.room.KickUserResp\x121\n" +
	"\bMuteUser\x12\x11.room.MuteUserReq\x1a\x12.room.MuteUserResp\x127\n" +
	"\n" +
	"UnmuteUser\x12\x13.room.UnmuteUserReq\x1a\x14.room.UnmuteUserRespB\x03Z\x01/b\x06proto3"

var (
	file_room_proto_rawDescOnce sync.Once
	file_room_proto_rawDescData []byte
)

func file_room_proto_rawDescGZIP() []byte {
	file_room_proto_rawDescOnce.Do(func() {
		file_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_proto_rawDesc), len(file_room_proto_rawDesc)))
	})
	return file_room_proto_rawDescData
}

var file_room_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_room_proto_goTypes = []any{
	(*KickUserReq)(nil),    // 0: room.KickUserReq
	(*KickUserResp)(nil),   // 1: room.KickUserResp
	(*MuteUserReq)(nil),    // 2: room.MuteUserReq
	(*MuteUserResp)(nil),   // 3: room.MuteUserResp
	(*UnmuteUserReq)(nil),  // 4: room.UnmuteUserReq
	(*UnmuteUserResp)(nil), // 5: room.UnmuteUserResp
}
var file_room_proto_depIdxs = []int32{
	0, // 0: room.Room.KickUser:input_type -> room.KickUserReq
	2, // 1: room.Room.MuteUser:input_type -> room.MuteUserReq
	4, // 2: room.Room.UnmuteUser:input_type -> room.UnmuteUserReq
	1, // 3: room.Room.KickUser:output_type -> room.KickUserResp
	3, // 4: room.Room.MuteUser:output_type -> room.MuteUserResp
	5, // 5: room.Room.UnmuteUser:output_type -> room.UnmuteUserResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_room_proto_init() }
func file_room_proto_init() {
	if File_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_proto_rawDesc), len(file_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_proto_goTypes,
		DependencyIndexes: file_room_proto_depIdxs,
		MessageInfos:      file_room_proto_msgTypes,
	}.Build()
	File_room_proto = out.File
	file_room_proto_goTypes = nil
	file_room_proto_depIdxs = nil
}
