// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: room.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamReq) Reset() {
	*x = StreamReq{}
	mi := &file_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamReq) ProtoMessage() {}

func (x *StreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamReq.ProtoReflect.Descriptor instead.
func (*StreamReq) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0}
}

func (x *StreamReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StreamResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greet         string                 `protobuf:"bytes,1,opt,name=greet,proto3" json:"greet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResp) Reset() {
	*x = StreamResp{}
	mi := &file_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResp) ProtoMessage() {}

func (x *StreamResp) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResp.ProtoReflect.Descriptor instead.
func (*StreamResp) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1}
}

func (x *StreamResp) GetGreet() string {
	if x != nil {
		return x.Greet
	}
	return ""
}

// 创建房间
type CreateRoomStreamReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TagId         int32                  `protobuf:"varint,3,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	IdCard        string                 `protobuf:"bytes,5,opt,name=idCard,proto3" json:"idCard,omitempty"`
	RealName      string                 `protobuf:"bytes,6,opt,name=realName,proto3" json:"realName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomStreamReq) Reset() {
	*x = CreateRoomStreamReq{}
	mi := &file_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomStreamReq) ProtoMessage() {}

func (x *CreateRoomStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomStreamReq.ProtoReflect.Descriptor instead.
func (*CreateRoomStreamReq) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoomStreamReq) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *CreateRoomStreamReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateRoomStreamReq) GetTagId() int32 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *CreateRoomStreamReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateRoomStreamReq) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

func (x *CreateRoomStreamReq) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

type CreateRoomStreamResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomStreamResp) Reset() {
	*x = CreateRoomStreamResp{}
	mi := &file_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomStreamResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomStreamResp) ProtoMessage() {}

func (x *CreateRoomStreamResp) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomStreamResp.ProtoReflect.Descriptor instead.
func (*CreateRoomStreamResp) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoomStreamResp) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 修改房间信息
type UpdateRoomStreamReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Announcement  string                 `protobuf:"bytes,1,opt,name=announcement,proto3" json:"announcement,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomStreamReq) Reset() {
	*x = UpdateRoomStreamReq{}
	mi := &file_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomStreamReq) ProtoMessage() {}

func (x *UpdateRoomStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomStreamReq.ProtoReflect.Descriptor instead.
func (*UpdateRoomStreamReq) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRoomStreamReq) GetAnnouncement() string {
	if x != nil {
		return x.Announcement
	}
	return ""
}

func (x *UpdateRoomStreamReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoomStreamReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateRoomStreamResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomStreamResp) Reset() {
	*x = UpdateRoomStreamResp{}
	mi := &file_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomStreamResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomStreamResp) ProtoMessage() {}

func (x *UpdateRoomStreamResp) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomStreamResp.ProtoReflect.Descriptor instead.
func (*UpdateRoomStreamResp) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRoomStreamResp) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 房间信息结构
type RoomInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomName       string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	UserId         uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OwnerNickname  string                 `protobuf:"bytes,4,opt,name=owner_nickname,json=ownerNickname,proto3" json:"owner_nickname,omitempty"`
	OwnerAvatar    string                 `protobuf:"bytes,5,opt,name=owner_avatar,json=ownerAvatar,proto3" json:"owner_avatar,omitempty"`
	RoomType       string                 `protobuf:"bytes,6,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
	Status         string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Announcement   string                 `protobuf:"bytes,8,opt,name=announcement,proto3" json:"announcement,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastActiveTime string                 `protobuf:"bytes,10,opt,name=last_active_time,json=lastActiveTime,proto3" json:"last_active_time,omitempty"`
	MemberCount    int32                  `protobuf:"varint,11,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	Image          string                 `protobuf:"bytes,12,opt,name=image,proto3" json:"image,omitempty"`
	TagId          uint64                 `protobuf:"varint,13,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	TagName        string                 `protobuf:"bytes,14,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{6}
}

func (x *RoomInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoomInfo) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *RoomInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RoomInfo) GetOwnerNickname() string {
	if x != nil {
		return x.OwnerNickname
	}
	return ""
}

func (x *RoomInfo) GetOwnerAvatar() string {
	if x != nil {
		return x.OwnerAvatar
	}
	return ""
}

func (x *RoomInfo) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *RoomInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RoomInfo) GetAnnouncement() string {
	if x != nil {
		return x.Announcement
	}
	return ""
}

func (x *RoomInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RoomInfo) GetLastActiveTime() string {
	if x != nil {
		return x.LastActiveTime
	}
	return ""
}

func (x *RoomInfo) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *RoomInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *RoomInfo) GetTagId() uint64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *RoomInfo) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

// 推荐房间接口
type GetRecommendRoomsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendRoomsReq) Reset() {
	*x = GetRecommendRoomsReq{}
	mi := &file_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendRoomsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendRoomsReq) ProtoMessage() {}

func (x *GetRecommendRoomsReq) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendRoomsReq.ProtoReflect.Descriptor instead.
func (*GetRecommendRoomsReq) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{7}
}

func (x *GetRecommendRoomsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRecommendRoomsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetRecommendRoomsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomInfo            `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendRoomsResp) Reset() {
	*x = GetRecommendRoomsResp{}
	mi := &file_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendRoomsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendRoomsResp) ProtoMessage() {}

func (x *GetRecommendRoomsResp) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendRoomsResp.ProtoReflect.Descriptor instead.
func (*GetRecommendRoomsResp) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{8}
}

func (x *GetRecommendRoomsResp) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *GetRecommendRoomsResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetRecommendRoomsResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRecommendRoomsResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetRecommendRoomsResp) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// 分类浏览接口
type GetRoomsByCategoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         uint64                 `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomsByCategoryReq) Reset() {
	*x = GetRoomsByCategoryReq{}
	mi := &file_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomsByCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsByCategoryReq) ProtoMessage() {}

func (x *GetRoomsByCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsByCategoryReq.ProtoReflect.Descriptor instead.
func (*GetRoomsByCategoryReq) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{9}
}

func (x *GetRoomsByCategoryReq) GetTagId() uint64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *GetRoomsByCategoryReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRoomsByCategoryReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetRoomsByCategoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomInfo            `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	CategoryName  string                 `protobuf:"bytes,6,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomsByCategoryResp) Reset() {
	*x = GetRoomsByCategoryResp{}
	mi := &file_room_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomsByCategoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsByCategoryResp) ProtoMessage() {}

func (x *GetRoomsByCategoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsByCategoryResp.ProtoReflect.Descriptor instead.
func (*GetRoomsByCategoryResp) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{10}
}

func (x *GetRoomsByCategoryResp) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *GetRoomsByCategoryResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetRoomsByCategoryResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRoomsByCategoryResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetRoomsByCategoryResp) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetRoomsByCategoryResp) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

// 搜索房间接口
type SearchRoomsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRoomsReq) Reset() {
	*x = SearchRoomsReq{}
	mi := &file_room_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRoomsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRoomsReq) ProtoMessage() {}

func (x *SearchRoomsReq) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRoomsReq.ProtoReflect.Descriptor instead.
func (*SearchRoomsReq) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{11}
}

func (x *SearchRoomsReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchRoomsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRoomsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchRoomsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomInfo            `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	Keyword       string                 `protobuf:"bytes,6,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRoomsResp) Reset() {
	*x = SearchRoomsResp{}
	mi := &file_room_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRoomsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRoomsResp) ProtoMessage() {}

func (x *SearchRoomsResp) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRoomsResp.ProtoReflect.Descriptor instead.
func (*SearchRoomsResp) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{12}
}

func (x *SearchRoomsResp) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *SearchRoomsResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchRoomsResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRoomsResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchRoomsResp) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *SearchRoomsResp) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

// 关闭房间接口
type CloseRoomStreamReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ClosedAt      string                 `protobuf:"bytes,3,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRoomStreamReq) Reset() {
	*x = CloseRoomStreamReq{}
	mi := &file_room_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRoomStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRoomStreamReq) ProtoMessage() {}

func (x *CloseRoomStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRoomStreamReq.ProtoReflect.Descriptor instead.
func (*CloseRoomStreamReq) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{13}
}

func (x *CloseRoomStreamReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CloseRoomStreamReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CloseRoomStreamReq) GetClosedAt() string {
	if x != nil {
		return x.ClosedAt
	}
	return ""
}

type CloseRoomStreamResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRoomStreamResp) Reset() {
	*x = CloseRoomStreamResp{}
	mi := &file_room_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRoomStreamResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRoomStreamResp) ProtoMessage() {}

func (x *CloseRoomStreamResp) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRoomStreamResp.ProtoReflect.Descriptor instead.
func (*CloseRoomStreamResp) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{14}
}

func (x *CloseRoomStreamResp) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_room_proto protoreflect.FileDescriptor

const file_room_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"room.proto\x12\x04room\"\x1f\n" +
	"\tStreamReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\"\n" +
	"\n" +
	"StreamResp\x12\x14\n" +
	"\x05greet\x18\x01 \x01(\tR\x05greet\"\xb0\x01\n" +
	"\x13CreateRoomStreamReq\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x15\n" +
	"\x06tag_id\x18\x03 \x01(\x05R\x05tagId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06idCard\x18\x05 \x01(\tR\x06idCard\x12\x1a\n" +
	"\brealName\x18\x06 \x01(\tR\brealName\"&\n" +
	"\x14CreateRoomStreamResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"a\n" +
	"\x13UpdateRoomStreamReq\x12\"\n" +
	"\fannouncement\x18\x01 \x01(\tR\fannouncement\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"&\n" +
	"\x14UpdateRoomStreamResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xa7\x03\n" +
	"\bRoomInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12%\n" +
	"\x0eowner_nickname\x18\x04 \x01(\tR\rownerNickname\x12!\n" +
	"\fowner_avatar\x18\x05 \x01(\tR\vownerAvatar\x12\x1b\n" +
	"\troom_type\x18\x06 \x01(\tR\broomType\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\"\n" +
	"\fannouncement\x18\b \x01(\tR\fannouncement\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12(\n" +
	"\x10last_active_time\x18\n" +
	" \x01(\tR\x0elastActiveTime\x12!\n" +
	"\fmember_count\x18\v \x01(\x05R\vmemberCount\x12\x14\n" +
	"\x05image\x18\f \x01(\tR\x05image\x12\x15\n" +
	"\x06tag_id\x18\r \x01(\x04R\x05tagId\x12\x19\n" +
	"\btag_name\x18\x0e \x01(\tR\atagName\"G\n" +
	"\x14GetRecommendRoomsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xa5\x01\n" +
	"\x15GetRecommendRoomsResp\x12$\n" +
	"\x05rooms\x18\x01 \x03(\v2\x0e.room.RoomInfoR\x05rooms\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"_\n" +
	"\x15GetRoomsByCategoryReq\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\x04R\x05tagId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xcb\x01\n" +
	"\x16GetRoomsByCategoryResp\x12$\n" +
	"\x05rooms\x18\x01 \x03(\v2\x0e.room.RoomInfoR\x05rooms\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\x12#\n" +
	"\rcategory_name\x18\x06 \x01(\tR\fcategoryName\"[\n" +
	"\x0eSearchRoomsReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xb9\x01\n" +
	"\x0fSearchRoomsResp\x12$\n" +
	"\x05rooms\x18\x01 \x03(\v2\x0e.room.RoomInfoR\x05rooms\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\x12\x18\n" +
	"\akeyword\x18\x06 \x01(\tR\akeyword\"Y\n" +
	"\x12CloseRoomStreamReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tclosed_at\x18\x03 \x01(\tR\bclosedAt\"%\n" +
	"\x13CloseRoomStreamResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id2\xd9\x03\n" +
	"\x04Room\x12*\n" +
	"\x05greet\x12\x0f.room.StreamReq\x1a\x10.room.StreamResp\x12@\n" +
	"\tCloseRoom\x12\x18.room.CloseRoomStreamReq\x1a\x19.room.CloseRoomStreamResp\x12C\n" +
	"\n" +
	"UpdateRoom\x12\x19.room.UpdateRoomStreamReq\x1a\x1a.room.UpdateRoomStreamResp\x12C\n" +
	"\n" +
	"CreateRoom\x12\x19.room.CreateRoomStreamReq\x1a\x1a.room.CreateRoomStreamResp\x12L\n" +
	"\x11GetRecommendRooms\x12\x1a.room.GetRecommendRoomsReq\x1a\x1b.room.GetRecommendRoomsResp\x12O\n" +
	"\x12GetRoomsByCategory\x12\x1b.room.GetRoomsByCategoryReq\x1a\x1c.room.GetRoomsByCategoryResp\x12:\n" +
	"\vSearchRooms\x12\x14.room.SearchRoomsReq\x1a\x15.room.SearchRoomsRespB\x03Z\x01/b\x06proto3"

var (
	file_room_proto_rawDescOnce sync.Once
	file_room_proto_rawDescData []byte
)

func file_room_proto_rawDescGZIP() []byte {
	file_room_proto_rawDescOnce.Do(func() {
		file_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_proto_rawDesc), len(file_room_proto_rawDesc)))
	})
	return file_room_proto_rawDescData
}

var file_room_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_room_proto_goTypes = []any{
	(*StreamReq)(nil),              // 0: room.StreamReq
	(*StreamResp)(nil),             // 1: room.StreamResp
	(*CreateRoomStreamReq)(nil),    // 2: room.CreateRoomStreamReq
	(*CreateRoomStreamResp)(nil),   // 3: room.CreateRoomStreamResp
	(*UpdateRoomStreamReq)(nil),    // 4: room.UpdateRoomStreamReq
	(*UpdateRoomStreamResp)(nil),   // 5: room.UpdateRoomStreamResp
	(*RoomInfo)(nil),               // 6: room.RoomInfo
	(*GetRecommendRoomsReq)(nil),   // 7: room.GetRecommendRoomsReq
	(*GetRecommendRoomsResp)(nil),  // 8: room.GetRecommendRoomsResp
	(*GetRoomsByCategoryReq)(nil),  // 9: room.GetRoomsByCategoryReq
	(*GetRoomsByCategoryResp)(nil), // 10: room.GetRoomsByCategoryResp
	(*SearchRoomsReq)(nil),         // 11: room.SearchRoomsReq
	(*SearchRoomsResp)(nil),        // 12: room.SearchRoomsResp
	(*CloseRoomStreamReq)(nil),     // 13: room.CloseRoomStreamReq
	(*CloseRoomStreamResp)(nil),    // 14: room.CloseRoomStreamResp
}
var file_room_proto_depIdxs = []int32{
	6,  // 0: room.GetRecommendRoomsResp.rooms:type_name -> room.RoomInfo
	6,  // 1: room.GetRoomsByCategoryResp.rooms:type_name -> room.RoomInfo
	6,  // 2: room.SearchRoomsResp.rooms:type_name -> room.RoomInfo
	0,  // 3: room.Room.greet:input_type -> room.StreamReq
	13, // 4: room.Room.CloseRoom:input_type -> room.CloseRoomStreamReq
	4,  // 5: room.Room.UpdateRoom:input_type -> room.UpdateRoomStreamReq
	2,  // 6: room.Room.CreateRoom:input_type -> room.CreateRoomStreamReq
	7,  // 7: room.Room.GetRecommendRooms:input_type -> room.GetRecommendRoomsReq
	9,  // 8: room.Room.GetRoomsByCategory:input_type -> room.GetRoomsByCategoryReq
	11, // 9: room.Room.SearchRooms:input_type -> room.SearchRoomsReq
	1,  // 10: room.Room.greet:output_type -> room.StreamResp
	14, // 11: room.Room.CloseRoom:output_type -> room.CloseRoomStreamResp
	5,  // 12: room.Room.UpdateRoom:output_type -> room.UpdateRoomStreamResp
	3,  // 13: room.Room.CreateRoom:output_type -> room.CreateRoomStreamResp
	8,  // 14: room.Room.GetRecommendRooms:output_type -> room.GetRecommendRoomsResp
	10, // 15: room.Room.GetRoomsByCategory:output_type -> room.GetRoomsByCategoryResp
	12, // 16: room.Room.SearchRooms:output_type -> room.SearchRoomsResp
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_room_proto_init() }
func file_room_proto_init() {
	if File_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_proto_rawDesc), len(file_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_proto_goTypes,
		DependencyIndexes: file_room_proto_depIdxs,
		MessageInfos:      file_room_proto_msgTypes,
	}.Build()
	File_room_proto = out.File
	file_room_proto_goTypes = nil
	file_room_proto_depIdxs = nil
}
