-- 创建麦位申请表
CREATE TABLE IF NOT EXISTS `mic_application` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '申请唯一ID',
  `room_id` bigint NOT NULL COMMENT '关联房间ID',
  `user_id` bigint unsigned NOT NULL COMMENT '申请用户ID',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '申请状态(0-待审批,1-已批准,2-已拒绝,3-已取消)',
  `apply_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '申请时间',
  `handle_time` datetime DEFAULT NULL COMMENT '处理时间',
  `handler_id` bigint unsigned DEFAULT NULL COMMENT '处理者ID',
  `reason` varchar(200) DEFAULT NULL COMMENT '拒绝原因',
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_mic_application_room_id` (`room_id`),
  KEY `idx_mic_application_user_id` (`user_id`),
  KEY `idx_mic_application_status` (`status`),
  KEY `idx_mic_application_room_status` (`room_id`, `status`),
  KEY `idx_mic_application_apply_time` (`apply_time`),
  KEY `idx_mic_application_handler` (`handler_id`),
  KEY `idx_mic_application_room_user` (`room_id`, `user_id`),
  CONSTRAINT `fk_mic_application_room` FOREIGN KEY (`room_id`) REFERENCES `room` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_mic_application_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_mic_application_handler` FOREIGN KEY (`handler_id`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_mic_application_status` CHECK (`status` IN (0, 1, 2, 3))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='麦位申请表';