-- 创建房间基础信息表
CREATE TABLE IF NOT EXISTS `room` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '房间唯一ID',
  `room_name` varchar(50) NOT NULL COMMENT '房间名称',
  `user_id` bigint unsigned NOT NULL COMMENT '房主用户ID，关联 user.id',
  `room_type` varchar(1) NOT NULL DEFAULT '0' COMMENT '房间类型(0-公开房,1-私密房)',
  `status` varchar(1) NOT NULL DEFAULT '0' COMMENT '房间状态(0-正常,1-已解散,2-全局禁言)',
  `announcement` varchar(200) DEFAULT NULL COMMENT '房间公告',
  `created_at` datetime(3) DEFAULT NULL,
  `closed_at` datetime DEFAULT NULL COMMENT '解散时间',
  `last_active_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后活跃时间',
  `fk_member_room` int NOT NULL DEFAULT '0' COMMENT '房间人数',
  `image` varchar(255) DEFAULT NULL COMMENT '房间封面图',
  `tag_id` bigint unsigned NOT NULL COMMENT '关联的标签ID（一个房间只能选一个）',
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `created_by` bigint DEFAULT NULL COMMENT '创建者',
  `updated_by` bigint DEFAULT NULL COMMENT '修改者',
  `deleted_by` bigint DEFAULT NULL COMMENT '删除者',
  PRIMARY KEY (`id`),
  KEY `idx_room_user_id` (`user_id`),
  KEY `idx_room_status` (`status`),
  KEY `idx_room_type` (`room_type`),
  KEY `idx_room_tag_id` (`tag_id`),
  KEY `idx_room_active_time` (`last_active_time`),
  KEY `idx_room_created_at` (`created_at`),
  CONSTRAINT `chk_room_type` CHECK (`room_type` IN ('0', '1')),
  CONSTRAINT `chk_room_status` CHECK (`status` IN ('0', '1', '2'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='房间基础信息表';